### ISSUE TITLE
regions: warning instead of error?

### ISSUE THREAD

**Issue by bturkus** [NYPL/ami-tools#60] opened 2021-09-17 17:36 UTC
hi,

not sure if i'm 100% on this, but it appears that validate_ami_bags throws an error with a "non ready for ingest" message anytime it encounters the region suffix. See convo here: https://trello.com/c/nChRN1Dj/703-2021002pami202scl5179

if this is indeed the case ,could we adjust this to a warning and remove the "not ready" message?

thanks,

ben

**Comment by nkrabben** [comment] 2021-09-17 17:46
I thought this was addressed by #58.
https://github.com/NYPL/ami-tools/commit/93727531100bc1ccd92836f59806c90372aba3c0#diff-2dcb8b260a229308e29bafce27c17d94dfd2fc8d72d078157d0cca9e31db7d20R91

Are you running the latest version? Only parts should be triggering an error, and all other r/s/t stuff should trigger a warning.

I'd also be up for rethinking the logic of this check, or making it something that can be called optionally.

**Comment by bturkus** [comment] 2021-09-17 17:51
just updated and receiving the same error. it's possible that I'm just not seeing the issue with these filenames, but they appear to be as they should be

**Comment by rdmarino** [comment] 2021-09-17 18:41
I'm also getting an error that says "Incorrect value for audioCodec. Expected: AAC, Found: AAC LC."
<img width="825" alt="Screen Shot 2021-09-17 at 2 37 48 PM" src="https://user-images.githubusercontent.com/40605190/133838059-9479530e-6214-4afb-b4f2-884a4e390127.png">

**Comment by nkrabben** [comment] 2021-09-17 18:48
For Ryan's error, I'll adjust the code to consider AAC and AAC LC equivalent.

**Comment by nkrabben** [comment] 2021-09-17 19:44
Addressed the audio codec things in #61

Realized that the error is caused by a typo in the shebang for validate_ami_bags, also fixed in #61 

Added guidance to rerun `pip install` when pulling down git updates

**Closed by nkrabben** 2021-09-17 19:44 UTC
